/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.klijent.view;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum;

/**
 *
 * @author Stefan
 */
public class PanelPretragraPolazaka extends javax.swing.JPanel {

    /**
     * Creates new form PanelPretragraPolazaka
     */
    public PanelPretragraPolazaka() {
        initComponents();
        this.setMinimumSize(new Dimension(1300, 490));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPocetnaStanica = new javax.swing.JComboBox();
        cmbKrajnjaStanica = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnPretraziPolaske = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePolasci = new javax.swing.JTable();
        lblNazivTabele = new javax.swing.JLabel();
        btnRezervisi = new javax.swing.JButton();
        btnViseOPolasku = new javax.swing.JButton();
        btnSviPolasciDanas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshTabela = new javax.swing.JButton();
        panelDatum1 = new rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(34, 40, 44));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_place_marker_32px.png"))); // NOI18N
        jLabel3.setText("Do:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, 40));

        jLabel4.setBackground(new java.awt.Color(34, 40, 44));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_user_location_32px.png"))); // NOI18N
        jLabel4.setText("Od:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 40));

        cmbPocetnaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbPocetnaStanica.setForeground(java.awt.Color.white);
        cmbPocetnaStanica.setBorder(null);
        add(cmbPocetnaStanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 340, 40));

        cmbKrajnjaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbKrajnjaStanica.setForeground(java.awt.Color.white);
        cmbKrajnjaStanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbKrajnjaStanica.setSelectedIndex(-1);
        cmbKrajnjaStanica.setToolTipText("");
        cmbKrajnjaStanica.setBorder(null);
        add(cmbKrajnjaStanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 340, 40));

        jLabel5.setBackground(new java.awt.Color(34, 40, 44));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_schedule_32px.png"))); // NOI18N
        jLabel5.setText("Datum:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 90, 40));

        btnPretraziPolaske.setBackground(new java.awt.Color(34, 40, 44));
        btnPretraziPolaske.setForeground(java.awt.Color.white);
        btnPretraziPolaske.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_google_web_search_64px.png"))); // NOI18N
        btnPretraziPolaske.setText("PRETRAZI POLASKE");
        btnPretraziPolaske.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPretraziPolaske.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnPretraziPolaske, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 340, 60));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablePolasci.setBackground(new java.awt.Color(153, 153, 153));
        tablePolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablePolasci.setMaximumSize(new java.awt.Dimension(600, 64));
        tablePolasci.setShowVerticalLines(false);
        tablePolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePolasci);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 830, 320));

        lblNazivTabele.setBackground(new java.awt.Color(34, 40, 44));
        lblNazivTabele.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNazivTabele.setForeground(java.awt.Color.white);
        add(lblNazivTabele, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 760, 40));

        btnRezervisi.setBackground(new java.awt.Color(34, 40, 44));
        btnRezervisi.setForeground(java.awt.Color.white);
        btnRezervisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_checked_64px.png"))); // NOI18N
        btnRezervisi.setText("REZERVISI POLAZAK");
        btnRezervisi.setBorder(null);
        btnRezervisi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnRezervisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, 270, 70));

        btnViseOPolasku.setBackground(new java.awt.Color(34, 40, 44));
        btnViseOPolasku.setForeground(java.awt.Color.white);
        btnViseOPolasku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_information_64px.png"))); // NOI18N
        btnViseOPolasku.setToolTipText("");
        btnViseOPolasku.setBorder(null);
        add(btnViseOPolasku, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 10, 100, 60));

        btnSviPolasciDanas.setBackground(new java.awt.Color(34, 40, 44));
        btnSviPolasciDanas.setForeground(java.awt.Color.white);
        btnSviPolasciDanas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_schedule_64px.png"))); // NOI18N
        btnSviPolasciDanas.setText("Danasnji polasci");
        btnSviPolasciDanas.setBorder(null);
        btnSviPolasciDanas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnSviPolasciDanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 200, 60));

        jLabel2.setBackground(new java.awt.Color(34, 40, 44));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_search_32px.png"))); // NOI18N
        jLabel2.setText("Pretraga:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        btnRefreshTabela.setBackground(new java.awt.Color(34, 40, 44));
        btnRefreshTabela.setForeground(java.awt.Color.white);
        btnRefreshTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_synchronize_64px_1.png"))); // NOI18N
        btnRefreshTabela.setBorder(null);
        btnRefreshTabela.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(btnRefreshTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 60, 60));
        add(panelDatum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 340, 40));
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnPretraziPolaske() {
        return btnPretraziPolaske;
    }

    public JButton getBtnRefreshTabela() {
        return btnRefreshTabela;
    }

    public JButton getBtnRezervisi() {
        return btnRezervisi;
    }

    public JButton getBtnSviPolasciDUGME() {
        return btnSviPolasciDanas;
    }

    public JComboBox getCmbKrajnjaStanica() {
        return cmbKrajnjaStanica;
    }

    public JComboBox getCmbPocetnaStanica() {
        return cmbPocetnaStanica;
    }

    public JButton getCmbViseOPolasku() {
        return btnViseOPolasku;
    }

    public PanelDatum getPanelDatum1() {
        return panelDatum1;
    }

    public JTable getTablePolasci() {
        return tablePolasci;
    }

    public JLabel getLblNazivTabele() {
        return lblNazivTabele;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziPolaske;
    private javax.swing.JButton btnRefreshTabela;
    private javax.swing.JButton btnRezervisi;
    private javax.swing.JButton btnSviPolasciDanas;
    private javax.swing.JButton btnViseOPolasku;
    private javax.swing.JComboBox cmbKrajnjaStanica;
    private javax.swing.JComboBox cmbPocetnaStanica;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNazivTabele;
    private rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum panelDatum1;
    private javax.swing.JTable tablePolasci;
    // End of variables declaration//GEN-END:variables

    public void btnRezervisiActionListener(ActionListener actionListener) {
        btnRezervisi.addActionListener(actionListener);
    }

    public void btnPretraziPolaskeActionListener(ActionListener actionListener) {
        btnPretraziPolaske.addActionListener(actionListener);
    }

    public void btnRefreshTabelaActionListener(ActionListener actionListener) {
        btnRefreshTabela.addActionListener(actionListener);
    }

    public void btnSviPolasciDanasActionListener(ActionListener actionListener) {
        btnSviPolasciDanas.addActionListener(actionListener);
    }
    public void btnViseOPolaskuActionListener(ActionListener actionListener) {
        btnViseOPolasku.addActionListener(actionListener);
    }

}
