/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.klijent.view;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum;

/**
 *
 * @author Stefan
 */
public class PanelPretragraPolazaka extends javax.swing.JPanel {

    /**
     * Creates new form PanelPretragraPolazaka
     */
    public PanelPretragraPolazaka() {
        initComponents();
        this.setMinimumSize(new Dimension(1300, 490));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDo = new javax.swing.JLabel();
        lblOd = new javax.swing.JLabel();
        cmbPocetnaStanica = new javax.swing.JComboBox();
        cmbKrajnjaStanica = new javax.swing.JComboBox();
        lblDatum = new javax.swing.JLabel();
        btnPretraziPolaske = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePolasci = new javax.swing.JTable();
        lblNazivTabele = new javax.swing.JLabel();
        btnRezervisi = new javax.swing.JButton();
        btnViseOPolasku = new javax.swing.JButton();
        btnSviPolasciDanas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshTabela = new javax.swing.JButton();
        panelDatum1 = new rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDo.setBackground(new java.awt.Color(34, 40, 44));
        lblDo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDo.setForeground(java.awt.Color.white);
        lblDo.setText("Do:");
        add(lblDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 110, 40));

        lblOd.setBackground(new java.awt.Color(34, 40, 44));
        lblOd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOd.setForeground(java.awt.Color.white);
        lblOd.setText("Od:");
        lblOd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(lblOd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 110, 40));

        cmbPocetnaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbPocetnaStanica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbPocetnaStanica.setForeground(java.awt.Color.white);
        cmbPocetnaStanica.setBorder(null);
        add(cmbPocetnaStanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 340, 40));

        cmbKrajnjaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbKrajnjaStanica.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbKrajnjaStanica.setForeground(java.awt.Color.white);
        cmbKrajnjaStanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbKrajnjaStanica.setSelectedIndex(-1);
        cmbKrajnjaStanica.setToolTipText("");
        cmbKrajnjaStanica.setBorder(null);
        add(cmbKrajnjaStanica, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 340, 40));

        lblDatum.setBackground(new java.awt.Color(34, 40, 44));
        lblDatum.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDatum.setForeground(java.awt.Color.white);
        lblDatum.setText("Datum:");
        add(lblDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 110, 40));

        btnPretraziPolaske.setBackground(new java.awt.Color(34, 40, 44));
        btnPretraziPolaske.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPretraziPolaske.setForeground(java.awt.Color.white);
        btnPretraziPolaske.setText("PRETRAZI POLASKE");
        btnPretraziPolaske.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnPretraziPolaske.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnPretraziPolaske, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 340, 60));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablePolasci.setBackground(new java.awt.Color(153, 153, 153));
        tablePolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablePolasci.setMaximumSize(new java.awt.Dimension(600, 64));
        tablePolasci.setShowVerticalLines(false);
        tablePolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePolasci);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 1280, 320));

        lblNazivTabele.setBackground(new java.awt.Color(34, 40, 44));
        lblNazivTabele.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNazivTabele.setForeground(java.awt.Color.white);
        add(lblNazivTabele, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 1140, 40));

        btnRezervisi.setBackground(new java.awt.Color(34, 40, 44));
        btnRezervisi.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRezervisi.setForeground(java.awt.Color.white);
        btnRezervisi.setText("Rezerviši kartu");
        btnRezervisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnRezervisi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnRezervisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 620, 270, 60));

        btnViseOPolasku.setBackground(new java.awt.Color(34, 40, 44));
        btnViseOPolasku.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnViseOPolasku.setForeground(java.awt.Color.white);
        btnViseOPolasku.setText("Informacije o polasku");
        btnViseOPolasku.setToolTipText("");
        btnViseOPolasku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(btnViseOPolasku, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 620, 270, 60));

        btnSviPolasciDanas.setBackground(new java.awt.Color(34, 40, 44));
        btnSviPolasciDanas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSviPolasciDanas.setForeground(java.awt.Color.white);
        btnSviPolasciDanas.setText("Današnji polasci");
        btnSviPolasciDanas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSviPolasciDanas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(btnSviPolasciDanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, 270, 60));

        jLabel2.setBackground(new java.awt.Color(34, 40, 44));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Pretraga:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        btnRefreshTabela.setBackground(new java.awt.Color(34, 40, 44));
        btnRefreshTabela.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefreshTabela.setForeground(java.awt.Color.white);
        btnRefreshTabela.setText("Osveži tabelu");
        btnRefreshTabela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(btnRefreshTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 210, 270, 60));
        add(panelDatum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 360, 60));
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnPretraziPolaske() {
        return btnPretraziPolaske;
    }

    public JButton getBtnRefreshTabela() {
        return btnRefreshTabela;
    }

    public JButton getBtnRezervisi() {
        return btnRezervisi;
    }

    public JButton getBtnSviPolasciDUGME() {
        return btnSviPolasciDanas;
    }

    public JComboBox getCmbKrajnjaStanica() {
        return cmbKrajnjaStanica;
    }

    public JComboBox getCmbPocetnaStanica() {
        return cmbPocetnaStanica;
    }

    public JButton getCmbViseOPolasku() {
        return btnViseOPolasku;
    }

    public PanelDatum getPanelDatum1() {
        return panelDatum1;
    }

    public JTable getTablePolasci() {
        return tablePolasci;
    }

    public JLabel getLblNazivTabele() {
        return lblNazivTabele;
    }

    public JButton getBtnSviPolasciDanas() {
        return btnSviPolasciDanas;
    }

    public JButton getBtnViseOPolasku() {
        return btnViseOPolasku;
    }

    public JLabel getLblDatum() {
        return lblDatum;
    }

    public JLabel getLblDo() {
        return lblDo;
    }

    public JLabel getLblOd() {
        return lblOd;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretraziPolaske;
    private javax.swing.JButton btnRefreshTabela;
    private javax.swing.JButton btnRezervisi;
    private javax.swing.JButton btnSviPolasciDanas;
    private javax.swing.JButton btnViseOPolasku;
    private javax.swing.JComboBox cmbKrajnjaStanica;
    private javax.swing.JComboBox cmbPocetnaStanica;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblDo;
    private javax.swing.JLabel lblNazivTabele;
    private javax.swing.JLabel lblOd;
    private rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum panelDatum1;
    private javax.swing.JTable tablePolasci;
    // End of variables declaration//GEN-END:variables

    public void btnRezervisiMouseListener(MouseListener mouseListener) {
        btnRezervisi.addMouseListener(mouseListener);
    }

    public void btnPretraziPolaskeMouseListener(MouseListener mouseListener) {
        btnPretraziPolaske.addMouseListener(mouseListener);
    }

    public void btnRefreshTabelaMouseListener(MouseListener mouseListener) {
        btnRefreshTabela.addMouseListener(mouseListener);
    }

    public void btnViseOPolaskuMouseListener(MouseListener mouseListener) {
        btnViseOPolasku.addMouseListener(mouseListener);
    }
    
    public void btnSviPolasciDanasMouseListener(MouseListener mouseListener) {
        btnSviPolasciDanas.addMouseListener(mouseListener);
    }

}
