/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.klijent.form;

import rs.stefanlezaic.zeleznice.srbije.lib.domen.Klijent;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.MedjuStanica;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Polazak;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Rezervacija;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Stanica;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import rs.stefanlezaic.zeleznice.srbije.klijent.kontroler.Kontroler;
import rs.stefanlezaic.zeleznice.srbije.klijent.modeli.tabela.ModelTabelePolasci;
import rs.stefanlezaic.zeleznice.srbije.klijent.modeli.tabela.ModelTabeleRezervacija;
import rs.stefanlezaic.zeleznice.srbije.lib.domen.Linija;
import rs.stefanlezaic.zeleznice.srbije.lib.exception.InvalidProductException;
import rs.stefanlezaic.zeleznice.srbije.lib.kalendar.Vreme;
import rs.stefanlezaic.zeleznice.srbije.lib.sat.Sat;
import rs.stefanlezaic.zeleznice.srbije.lib.swing.Tabela;
import rs.stefanlezaic.zeleznice.srbije.lib.theme.Tema;
import rs.stefanlezaic.zeleznice.srbije.lib.view.dialog.JOptionPaneExample;
import rs.stefanlezaic.zeleznice.srbije.lib.view.dialog.PanelAttention;
import rs.stefanlezaic.zeleznice.srbije.lib.view.dialog.PanelError;
import rs.stefanlezaic.zeleznice.srbije.lib.view.dialog.PanelSuccess;

/**
 *
 * @author sleza
 */
public final class FormaRezervacije extends javax.swing.JFrame {

    private Klijent k;
    SimpleDateFormat smf = new SimpleDateFormat("dd.MM.yyyy");
    ModelTabelePolasci mtp = new ModelTabelePolasci();
    ModelTabeleRezervacija mtr = new ModelTabeleRezervacija();
    ArrayList<Rezervacija> listaRezervacija = new ArrayList<>();
    ArrayList<MedjuStanica> listaMedjustanica = new ArrayList<>();
    Sat sat;
    Tema tema;
    Tabela tabela;
    public static int BROJ_PRIKAZA = 0;
    public static int DUGME = 0;

    /**
     * Creates new form FormaRezervacije
     */
    public FormaRezervacije() {
        initComponents();
        this.setSize(1336, 768);
        postaviVelicinuPanela(1336, 768);
        tema = new Tema(this);
        panelDatum1.postavi(10, Vreme.Unapred);
        panelDatum1.postaviDanasnjiDatum();
        tabela = new Tabela();
        tabela.urediTabelu(tablePolasci);
        tabela.urediTabelu(tabelMojeRezeravacije);
        ukljuciDarkMode();
        centrirajFrame();
        menuOdjavaSaDesneStrane();
        pokreniPanelRezervacija();
        srediTabelu();
        ucitajStanice();
        ucitajMedjustanice();
        pretraziZaDatumPolaske(new Date());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblWhiteMode = new javax.swing.JLabel();
        lblDarkMode = new javax.swing.JLabel();
        lblSat = new javax.swing.JLabel();
        panelKlijenta = new javax.swing.JPanel();
        lblEmailRegistracija = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblImeRegistracija = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        lblPrezimeRegistracija = new javax.swing.JLabel();
        txtPrezime = new javax.swing.JTextField();
        lblKorisnickoImeRegistracija = new javax.swing.JLabel();
        txtKorisnickoIme = new javax.swing.JTextField();
        lblLozinakRegistracija = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPotvrdaLozinkeRegistracija = new javax.swing.JLabel();
        txtPasswordPotvrda = new javax.swing.JPasswordField();
        btnPromeni = new javax.swing.JButton();
        panelRezervacije = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbPocetnaStanica = new javax.swing.JComboBox();
        cmbKrajnjaStanica = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnPretraziPolaske = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePolasci = new javax.swing.JTable();
        lblNazivTabele = new javax.swing.JLabel();
        btnRezervisi = new javax.swing.JButton();
        cmbViseOPolasku = new javax.swing.JButton();
        btnSviPolasciDUGME = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnRefreshTabela = new javax.swing.JButton();
        panelDatum1 = new rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum();
        panelMojeRezervacije = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelMojeRezeravacije = new javax.swing.JTable();
        lblNazivTabeleMojeRezervacije = new javax.swing.JLabel();
        cmbAktivneRezervacije = new javax.swing.JButton();
        btnRealizovaneRezervacije = new javax.swing.JButton();
        btnOtkaziRezervaciju = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menuPretraga = new javax.swing.JMenu();
        menuNalog = new javax.swing.JMenu();
        menuMojeRezervacije = new javax.swing.JMenu();
        jMenuOdjava = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(44, 44, 44));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(java.awt.Color.white);
        jSeparator1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSeparator1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 0, 1336, 10);

        lblWhiteMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblWhiteMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/whiteMode.png"))); // NOI18N
        lblWhiteMode.setText("White theme");
        lblWhiteMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblWhiteModeMouseClicked(evt);
            }
        });
        getContentPane().add(lblWhiteMode);
        lblWhiteMode.setBounds(10, 10, 190, 50);

        lblDarkMode.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDarkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/darkMode.png"))); // NOI18N
        lblDarkMode.setText("Dark theme");
        lblDarkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDarkModeMouseClicked(evt);
            }
        });
        getContentPane().add(lblDarkMode);
        lblDarkMode.setBounds(10, 10, 190, 50);

        lblSat.setBackground(new java.awt.Color(34, 40, 44));
        lblSat.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblSat.setForeground(java.awt.Color.white);
        lblSat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_schedule_64px.png"))); // NOI18N
        lblSat.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblSat);
        lblSat.setBounds(860, 700, 440, 60);

        panelKlijenta.setBackground(new java.awt.Color(44, 44, 44));
        panelKlijenta.setForeground(new java.awt.Color(255, 255, 255));
        panelKlijenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.setMaximumSize(new java.awt.Dimension(1336, 768));
        panelKlijenta.setLayout(null);

        lblEmailRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblEmailRegistracija.setForeground(java.awt.Color.white);
        lblEmailRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_email_sign_32px_1.png"))); // NOI18N
        lblEmailRegistracija.setText("Email:");
        lblEmailRegistracija.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(lblEmailRegistracija);
        lblEmailRegistracija.setBounds(130, 100, 140, 30);

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setForeground(java.awt.Color.black);
        txtEmail.setBorder(null);
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtEmail.setEnabled(false);
        panelKlijenta.add(txtEmail);
        txtEmail.setBounds(280, 100, 218, 30);

        lblImeRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblImeRegistracija.setForeground(java.awt.Color.white);
        lblImeRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_name_tag_32px.png"))); // NOI18N
        lblImeRegistracija.setText("Ime:");
        panelKlijenta.add(lblImeRegistracija);
        lblImeRegistracija.setBounds(130, 140, 140, 30);

        txtIme.setBackground(new java.awt.Color(102, 102, 102));
        txtIme.setForeground(java.awt.Color.black);
        txtIme.setBorder(null);
        txtIme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtIme.setEnabled(false);
        panelKlijenta.add(txtIme);
        txtIme.setBounds(280, 140, 218, 30);

        lblPrezimeRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblPrezimeRegistracija.setForeground(java.awt.Color.white);
        lblPrezimeRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_name_tag_32px.png"))); // NOI18N
        lblPrezimeRegistracija.setText("Prezime:");
        lblPrezimeRegistracija.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(lblPrezimeRegistracija);
        lblPrezimeRegistracija.setBounds(130, 180, 140, 30);

        txtPrezime.setBackground(new java.awt.Color(102, 102, 102));
        txtPrezime.setForeground(java.awt.Color.black);
        txtPrezime.setBorder(null);
        txtPrezime.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtPrezime.setEnabled(false);
        panelKlijenta.add(txtPrezime);
        txtPrezime.setBounds(280, 180, 218, 30);

        lblKorisnickoImeRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblKorisnickoImeRegistracija.setForeground(java.awt.Color.white);
        lblKorisnickoImeRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_name_32px.png"))); // NOI18N
        lblKorisnickoImeRegistracija.setText("Korisnicko ime:");
        lblKorisnickoImeRegistracija.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(lblKorisnickoImeRegistracija);
        lblKorisnickoImeRegistracija.setBounds(130, 220, 140, 30);

        txtKorisnickoIme.setBackground(new java.awt.Color(102, 102, 102));
        txtKorisnickoIme.setForeground(java.awt.Color.black);
        txtKorisnickoIme.setBorder(null);
        txtKorisnickoIme.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(txtKorisnickoIme);
        txtKorisnickoIme.setBounds(280, 220, 218, 30);

        lblLozinakRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblLozinakRegistracija.setForeground(java.awt.Color.white);
        lblLozinakRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_key_32px.png"))); // NOI18N
        lblLozinakRegistracija.setText("Lozinka:");
        lblLozinakRegistracija.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(lblLozinakRegistracija);
        lblLozinakRegistracija.setBounds(130, 260, 140, 30);

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setForeground(java.awt.Color.black);
        txtPassword.setBorder(null);
        txtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(txtPassword);
        txtPassword.setBounds(280, 260, 218, 30);

        lblPotvrdaLozinkeRegistracija.setBackground(new java.awt.Color(34, 40, 44));
        lblPotvrdaLozinkeRegistracija.setForeground(java.awt.Color.white);
        lblPotvrdaLozinkeRegistracija.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_grand_master_key_32px.png"))); // NOI18N
        lblPotvrdaLozinkeRegistracija.setText("Potvrda loznike:");
        lblPotvrdaLozinkeRegistracija.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(lblPotvrdaLozinkeRegistracija);
        lblPotvrdaLozinkeRegistracija.setBounds(130, 300, 140, 30);

        txtPasswordPotvrda.setBackground(new java.awt.Color(102, 102, 102));
        txtPasswordPotvrda.setForeground(java.awt.Color.black);
        txtPasswordPotvrda.setBorder(null);
        txtPasswordPotvrda.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelKlijenta.add(txtPasswordPotvrda);
        txtPasswordPotvrda.setBounds(280, 300, 218, 30);

        btnPromeni.setBackground(new java.awt.Color(34, 40, 44));
        btnPromeni.setForeground(java.awt.Color.white);
        btnPromeni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_update_64px.png"))); // NOI18N
        btnPromeni.setText("Promeni");
        btnPromeni.setBorder(null);
        btnPromeni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPromeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPromeniActionPerformed(evt);
            }
        });
        panelKlijenta.add(btnPromeni);
        btnPromeni.setBounds(280, 342, 218, 60);

        getContentPane().add(panelKlijenta);
        panelKlijenta.setBounds(0, 0, 1336, 768);

        panelRezervacije.setBackground(new java.awt.Color(44, 44, 44));
        panelRezervacije.setForeground(new java.awt.Color(255, 255, 255));
        panelRezervacije.setToolTipText("");
        panelRezervacije.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRezervacije.setMaximumSize(new java.awt.Dimension(1336, 768));
        panelRezervacije.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(34, 40, 44));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_place_marker_32px.png"))); // NOI18N
        jLabel3.setText("Do:");
        panelRezervacije.add(jLabel3);
        jLabel3.setBounds(10, 220, 100, 40);

        jLabel4.setBackground(new java.awt.Color(34, 40, 44));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_user_location_32px.png"))); // NOI18N
        jLabel4.setText("Od:");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRezervacije.add(jLabel4);
        jLabel4.setBounds(10, 160, 100, 40);
        jLabel4.getAccessibleContext().setAccessibleDescription("");

        cmbPocetnaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbPocetnaStanica.setForeground(java.awt.Color.white);
        cmbPocetnaStanica.setBorder(null);
        panelRezervacije.add(cmbPocetnaStanica);
        cmbPocetnaStanica.setBounds(120, 160, 340, 40);

        cmbKrajnjaStanica.setBackground(new java.awt.Color(34, 40, 44));
        cmbKrajnjaStanica.setForeground(java.awt.Color.white);
        cmbKrajnjaStanica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        cmbKrajnjaStanica.setSelectedIndex(-1);
        cmbKrajnjaStanica.setToolTipText("");
        cmbKrajnjaStanica.setBorder(null);
        panelRezervacije.add(cmbKrajnjaStanica);
        cmbKrajnjaStanica.setBounds(120, 220, 340, 40);

        jLabel5.setBackground(new java.awt.Color(34, 40, 44));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_schedule_32px.png"))); // NOI18N
        jLabel5.setText("Datum:");
        panelRezervacije.add(jLabel5);
        jLabel5.setBounds(10, 280, 100, 40);

        btnPretraziPolaske.setBackground(new java.awt.Color(34, 40, 44));
        btnPretraziPolaske.setForeground(java.awt.Color.white);
        btnPretraziPolaske.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_google_web_search_64px.png"))); // NOI18N
        btnPretraziPolaske.setText("PRETRAZI POLASKE");
        btnPretraziPolaske.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPretraziPolaske.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPretraziPolaske.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziPolaskeActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnPretraziPolaske);
        btnPretraziPolaske.setBounds(120, 340, 270, 60);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tablePolasci.setBackground(new java.awt.Color(153, 153, 153));
        tablePolasci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePolasci.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tablePolasci.setMaximumSize(new java.awt.Dimension(600, 64));
        tablePolasci.setShowVerticalLines(false);
        tablePolasci.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tablePolasci);

        panelRezervacije.add(jScrollPane2);
        jScrollPane2.setBounds(470, 160, 830, 320);

        lblNazivTabele.setBackground(new java.awt.Color(34, 40, 44));
        lblNazivTabele.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblNazivTabele.setForeground(java.awt.Color.white);
        panelRezervacije.add(lblNazivTabele);
        lblNazivTabele.setBounds(140, 110, 700, 40);

        btnRezervisi.setBackground(new java.awt.Color(34, 40, 44));
        btnRezervisi.setForeground(java.awt.Color.white);
        btnRezervisi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_checked_64px.png"))); // NOI18N
        btnRezervisi.setText("REZERVISI POLAZAK");
        btnRezervisi.setBorder(null);
        btnRezervisi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRezervisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRezervisiActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnRezervisi);
        btnRezervisi.setBounds(1030, 490, 270, 70);

        cmbViseOPolasku.setBackground(new java.awt.Color(34, 40, 44));
        cmbViseOPolasku.setForeground(java.awt.Color.white);
        cmbViseOPolasku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_information_64px.png"))); // NOI18N
        cmbViseOPolasku.setToolTipText("");
        cmbViseOPolasku.setBorder(null);
        cmbViseOPolasku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViseOPolaskuActionPerformed(evt);
            }
        });
        panelRezervacije.add(cmbViseOPolasku);
        cmbViseOPolasku.setBounds(1200, 90, 100, 60);
        cmbViseOPolasku.getAccessibleContext().setAccessibleDescription("Stanica");

        btnSviPolasciDUGME.setBackground(new java.awt.Color(34, 40, 44));
        btnSviPolasciDUGME.setForeground(java.awt.Color.white);
        btnSviPolasciDUGME.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_schedule_64px.png"))); // NOI18N
        btnSviPolasciDUGME.setText("Danasnji polasci");
        btnSviPolasciDUGME.setBorder(null);
        btnSviPolasciDUGME.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSviPolasciDUGME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSviPolasciDUGMEActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnSviPolasciDUGME);
        btnSviPolasciDUGME.setBounds(990, 90, 200, 60);

        jLabel2.setBackground(new java.awt.Color(34, 40, 44));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_search_32px.png"))); // NOI18N
        jLabel2.setText("Pretraga:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelRezervacije.add(jLabel2);
        jLabel2.setBounds(10, 110, 130, 40);

        btnRefreshTabela.setBackground(new java.awt.Color(34, 40, 44));
        btnRefreshTabela.setForeground(java.awt.Color.white);
        btnRefreshTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_synchronize_64px_1.png"))); // NOI18N
        btnRefreshTabela.setBorder(null);
        btnRefreshTabela.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRefreshTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshTabelaActionPerformed(evt);
            }
        });
        panelRezervacije.add(btnRefreshTabela);
        btnRefreshTabela.setBounds(920, 90, 64, 60);
        btnRefreshTabela.getAccessibleContext().setAccessibleDescription("Osvezi tabelu");

        panelRezervacije.add(panelDatum1);
        panelDatum1.setBounds(120, 280, 340, 40);

        getContentPane().add(panelRezervacije);
        panelRezervacije.setBounds(0, 0, 1336, 768);

        panelMojeRezervacije.setBackground(new java.awt.Color(44, 44, 44));
        panelMojeRezervacije.setForeground(new java.awt.Color(255, 255, 255));
        panelMojeRezervacije.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelMojeRezervacije.setMaximumSize(new java.awt.Dimension(1336, 768));
        panelMojeRezervacije.setMinimumSize(new java.awt.Dimension(1336, 768));
        panelMojeRezervacije.setPreferredSize(new java.awt.Dimension(1336, 768));
        panelMojeRezervacije.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(java.awt.Color.white);
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tabelMojeRezeravacije.setForeground(new java.awt.Color(0, 0, 0));
        tabelMojeRezeravacije.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMojeRezeravacije.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelMojeRezeravacije.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabelMojeRezeravacije.setMaximumSize(new java.awt.Dimension(100, 64));
        tabelMojeRezeravacije.setMinimumSize(new java.awt.Dimension(1100, 64));
        tabelMojeRezeravacije.setShowVerticalLines(false);
        tabelMojeRezeravacije.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelMojeRezeravacije);

        panelMojeRezervacije.add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 1270, 220);

        lblNazivTabeleMojeRezervacije.setBackground(new java.awt.Color(34, 40, 44));
        lblNazivTabeleMojeRezervacije.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblNazivTabeleMojeRezervacije.setForeground(java.awt.Color.white);
        lblNazivTabeleMojeRezervacije.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNazivTabeleMojeRezervacije.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_grid_64px.png"))); // NOI18N
        lblNazivTabeleMojeRezervacije.setText("Tabela rezervacija:");
        panelMojeRezervacije.add(lblNazivTabeleMojeRezervacije);
        lblNazivTabeleMojeRezervacije.setBounds(10, 90, 840, 40);

        cmbAktivneRezervacije.setBackground(new java.awt.Color(34, 40, 44));
        cmbAktivneRezervacije.setForeground(java.awt.Color.white);
        cmbAktivneRezervacije.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_calendar_64px.png"))); // NOI18N
        cmbAktivneRezervacije.setText("Aktivne rezervacije");
        cmbAktivneRezervacije.setBorder(null);
        cmbAktivneRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAktivneRezervacijeActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(cmbAktivneRezervacije);
        cmbAktivneRezervacije.setBounds(850, 80, 230, 60);

        btnRealizovaneRezervacije.setBackground(new java.awt.Color(34, 40, 44));
        btnRealizovaneRezervacije.setForeground(java.awt.Color.white);
        btnRealizovaneRezervacije.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_checked_64px.png"))); // NOI18N
        btnRealizovaneRezervacije.setText("Realizovane rezervacije");
        btnRealizovaneRezervacije.setBorder(null);
        btnRealizovaneRezervacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizovaneRezervacijeActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(btnRealizovaneRezervacije);
        btnRealizovaneRezervacije.setBounds(1080, 80, 210, 60);

        btnOtkaziRezervaciju.setBackground(new java.awt.Color(34, 40, 44));
        btnOtkaziRezervaciju.setForeground(java.awt.Color.white);
        btnOtkaziRezervaciju.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_cancel_64px.png"))); // NOI18N
        btnOtkaziRezervaciju.setText("Oktazi rezervaciju");
        btnOtkaziRezervaciju.setBorder(null);
        btnOtkaziRezervaciju.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnOtkaziRezervaciju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtkaziRezervacijuActionPerformed(evt);
            }
        });
        panelMojeRezervacije.add(btnOtkaziRezervaciju);
        btnOtkaziRezervaciju.setBounds(980, 380, 310, 60);

        getContentPane().add(panelMojeRezervacije);
        panelMojeRezervacije.setBounds(0, 0, 1340, 768);

        Menu.setMaximumSize(new java.awt.Dimension(1336, 80));
        Menu.setMinimumSize(new java.awt.Dimension(1336, 80));
        Menu.setPreferredSize(new java.awt.Dimension(1336, 80));

        menuPretraga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/meniPretraga.png"))); // NOI18N
        menuPretraga.setText("Pretraga");
        menuPretraga.setMaximumSize(new java.awt.Dimension(200, 80));
        menuPretraga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuPretragaMouseClicked(evt);
            }
        });
        Menu.add(menuPretraga);

        menuNalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/meniNalog.png"))); // NOI18N
        menuNalog.setText("Nalog");
        menuNalog.setMaximumSize(new java.awt.Dimension(200, 80));
        menuNalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNalogMouseClicked(evt);
            }
        });
        Menu.add(menuNalog);

        menuMojeRezervacije.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/meniRezervacije.png"))); // NOI18N
        menuMojeRezervacije.setText("Moje rezervacije");
        menuMojeRezervacije.setMaximumSize(new java.awt.Dimension(200, 80));
        menuMojeRezervacije.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMojeRezervacijeMouseClicked(evt);
            }
        });
        Menu.add(menuMojeRezervacije);

        jMenuOdjava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rs/stefanlezaic/zeleznice/srbije/klijent/resources/icons/icons8_shutdown_100px.png"))); // NOI18N
        jMenuOdjava.setText("Odjavi se");
        jMenuOdjava.setMaximumSize(new java.awt.Dimension(200, 80));
        jMenuOdjava.setMinimumSize(new java.awt.Dimension(200, 30));
        jMenuOdjava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuOdjavaMouseClicked(evt);
            }
        });
        Menu.add(jMenuOdjava);

        setJMenuBar(Menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziPolaskeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziPolaskeActionPerformed
        DUGME = 1;
        pretraziPolaskeZaDatum();
    }//GEN-LAST:event_btnPretraziPolaskeActionPerformed

    private void btnRezervisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRezervisiActionPerformed
        int red = tablePolasci.getSelectedRow();
        if (red == -1) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Morate izabrati polazak!"));
            return;
        }
        Polazak p = mtp.vratiListu().get(red);
//        if (p.getNapomena() != null && (p.getNapomena().contains("OTKAZANO") || p.getNapomena().contains("Otkazano") || p.getNapomena().contains("Otkazan"))) {
//            JOptionPane.showMessageDialog(this, "Polazak je otkazan. Ne mozete ga rezervisati!");
//            return;
//        }
        //ovo moze u validaciji
//        if (p.getDatumPolaska().before(new Date())) {
//            JOptionPane.showMessageDialog(this, "Ne mozete rezervisati kartu za polazak koji je vec realizovan!");
//            return;
//        }
//        Rezervacija rez = new Rezervacija(null, p, null);
//        boolean popunjeno = mtp.popunjeno(rez);
//        if (!popunjeno) {
//            pretraziPolaskeZaDatum();
//        } else {
//            JOptionPane.showMessageDialog(this, "Popunjena su sva mesta!");
//        }
        Date d = new Date();
        Rezervacija r = new Rezervacija(k, p, d);
        try {
            Kontroler.getInstance().rezervisiPolazak(r);
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelSuccess("Uspesno ste rezervisali kartu za polazak!"));
//            btnRefreshTabelaActionPerformed(evt);
        } catch (Exception ex) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelError(ex.getMessage()));
        }

    }//GEN-LAST:event_btnRezervisiActionPerformed

    private void btnPromeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPromeniActionPerformed
        String ime = txtIme.getText();
        String prezime = txtPrezime.getText();
        String email = txtEmail.getText();
        String korisnickoIme = txtKorisnickoIme.getText();
        char[] niz = txtPassword.getPassword();
        String lozinka = String.copyValueOf(niz);
        char[] niz2 = txtPasswordPotvrda.getPassword();
        String lozinka2 = String.copyValueOf(niz2);
        if (k.getKorisnickoIme().equals(korisnickoIme) && lozinka.isEmpty() && lozinka2.isEmpty()) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Niste napravili nikakvu promenu!"));
            return;
        }
        if (lozinka.isEmpty() && lozinka2.isEmpty()) {
            lozinka = k.getLozinka();
            lozinka2 = k.getLozinka();
        }
        if (!lozinka.equals(lozinka2)) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Potrvrda lozinke nije dobra!"));
            return;
        }
        Klijent klijent = new Klijent(k.getKlijentID(), korisnickoIme, lozinka, ime, prezime, email);
        try {
            Kontroler.getInstance().IzmeniNalog(klijent);
            k = klijent;
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelSuccess("Uspesno ste izmenili podatake!"));
        } catch (Exception ex) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelError(ex.toString()));
        } finally {
            txtPassword.setText("");
            txtPasswordPotvrda.setText("");
        }
    }//GEN-LAST:event_btnPromeniActionPerformed

    private void cmbAktivneRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAktivneRezervacijeActionPerformed
        Date datum = new Date();
        ArrayList<Rezervacija> listaAkt = new ArrayList<>();
        for (Rezervacija rezervacija : listaRezervacija) {
            if (datum.before(rezervacija.getPolazak().getDatumPolaska())) {
                listaAkt.add(rezervacija);
            }
        }
        if (!listaAkt.isEmpty()) {
            mtr.ocistiTabelu();
            mtr.setList(listaAkt);
        } else {
            mtr.ocistiTabelu();
        }
    }//GEN-LAST:event_cmbAktivneRezervacijeActionPerformed

    private void btnRealizovaneRezervacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizovaneRezervacijeActionPerformed
        Date datum = new Date();
        ArrayList<Rezervacija> listaRealizovanih = new ArrayList<>();
        for (Rezervacija rezervacija : listaRezervacija) {
            if (datum.after(rezervacija.getPolazak().getDatumPolaska())) {
                listaRealizovanih.add(rezervacija);
            }
        }
        if (!listaRealizovanih.isEmpty()) {
            mtr.ocistiTabelu();
            mtr.setList(listaRealizovanih);
        } else {
            mtr.ocistiTabelu();
        }

    }//GEN-LAST:event_btnRealizovaneRezervacijeActionPerformed

    private void btnOtkaziRezervacijuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtkaziRezervacijuActionPerformed
        int broj = tabelMojeRezeravacije.getSelectedRow();
        if (broj == -1) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Izaberite polazak!"));
            return;
        }
        Rezervacija r = mtr.getList().get(broj);
        Date danasnji = new Date();

        //Ovo bi trebalo da ide u validaciju
        if (danasnji.after(r.getPolazak().getDatumPolaska())) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Polazak je vec realizovan!"));
            return;
        }
        try {
            Kontroler.getInstance().otkaziRezervaciju(r);
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelSuccess("Uspesno ste otkazali rezervaciju!"));
            mtr.izbrisiIzTabele(broj);
        } catch (InvalidProductException ex) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelError(ex.toString()));
        } catch (Exception ex) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelError(ex.toString()));

        }
    }//GEN-LAST:event_btnOtkaziRezervacijuActionPerformed

    private void cmbViseOPolaskuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViseOPolaskuActionPerformed
        int broj = tablePolasci.getSelectedRow();
        if (broj == -1) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Izaberite polazak za koji zelite da vidite sve medjustanice!"));
            return;
        }
        Polazak p = mtp.getList().get(broj);
        MedjuStanica m = new MedjuStanica(null, p.getLinija(), 0);
        ArrayList<MedjuStanica> listaMedjustanica;
        try {
            listaMedjustanica = Kontroler.getInstance().vratiMiMedjustaniceLiniju(m);
            JOptionPane.showMessageDialog(this, ispisiListu(listaMedjustanica), p.getLinija().getStanicaPocetna() + "-" + p.getLinija().getStanicaKrajnja() + " (" + p.getLinija().getTipLinije() + ")", 1);
        } catch (Exception ex) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelError(ex.toString()));
        }
    }//GEN-LAST:event_cmbViseOPolaskuActionPerformed

    private void btnSviPolasciDUGMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSviPolasciDUGMEActionPerformed
        DUGME = 0;
        try {
            pretraziZaDatumPolaske(new Date());
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSviPolasciDUGMEActionPerformed

    private void btnRefreshTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshTabelaActionPerformed
        if (DUGME == 0) {
            pretraziZaDatumPolaske(new Date());
        } else {
            pretraziPolaskeZaDatum();
        }
    }//GEN-LAST:event_btnRefreshTabelaActionPerformed

    private void menuPretragaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuPretragaMouseClicked
        pokreniPanelRezervacija();
    }//GEN-LAST:event_menuPretragaMouseClicked

    private void menuNalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNalogMouseClicked
        pokreniPanelNalog();

    }//GEN-LAST:event_menuNalogMouseClicked

    private void menuMojeRezervacijeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMojeRezervacijeMouseClicked
        pokreniPanelMojeRezervacije();
        ucitajMojeRezervacije();
    }//GEN-LAST:event_menuMojeRezervacijeMouseClicked

    private void jMenuOdjavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuOdjavaMouseClicked
        odjaviSe();
    }//GEN-LAST:event_jMenuOdjavaMouseClicked

    private void lblDarkModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDarkModeMouseClicked
        ukljuciDarkMode();
    }//GEN-LAST:event_lblDarkModeMouseClicked

    private void lblWhiteModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblWhiteModeMouseClicked
        iskljuciDarkMode();
    }//GEN-LAST:event_lblWhiteModeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton btnOtkaziRezervaciju;
    private javax.swing.JButton btnPretraziPolaske;
    private javax.swing.JButton btnPromeni;
    private javax.swing.JButton btnRealizovaneRezervacije;
    private javax.swing.JButton btnRefreshTabela;
    private javax.swing.JButton btnRezervisi;
    private javax.swing.JButton btnSviPolasciDUGME;
    private javax.swing.JButton cmbAktivneRezervacije;
    private javax.swing.JComboBox cmbKrajnjaStanica;
    private javax.swing.JComboBox cmbPocetnaStanica;
    private javax.swing.JButton cmbViseOPolasku;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenuOdjava;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDarkMode;
    private javax.swing.JLabel lblEmailRegistracija;
    private javax.swing.JLabel lblImeRegistracija;
    private javax.swing.JLabel lblKorisnickoImeRegistracija;
    private javax.swing.JLabel lblLozinakRegistracija;
    private javax.swing.JLabel lblNazivTabele;
    private javax.swing.JLabel lblNazivTabeleMojeRezervacije;
    private javax.swing.JLabel lblPotvrdaLozinkeRegistracija;
    private javax.swing.JLabel lblPrezimeRegistracija;
    private javax.swing.JLabel lblSat;
    private javax.swing.JLabel lblWhiteMode;
    private javax.swing.JMenu menuMojeRezervacije;
    private javax.swing.JMenu menuNalog;
    private javax.swing.JMenu menuPretraga;
    private rs.stefanlezaic.zeleznice.srbije.lib.view.PanelDatum panelDatum1;
    private javax.swing.JPanel panelKlijenta;
    private javax.swing.JPanel panelMojeRezervacije;
    private javax.swing.JPanel panelRezervacije;
    private javax.swing.JTable tabelMojeRezeravacije;
    private javax.swing.JTable tablePolasci;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtKorisnickoIme;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordPotvrda;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables

    public Klijent getK() {
        return k;
    }

    public void setK(Klijent k) {
        this.k = k;
        txtEmail.setText(k.getEmail());
        txtIme.setText(k.getIme());
        txtPrezime.setText(k.getPrezime());
        txtKorisnickoIme.setText(k.getKorisnickoIme());
    }

    private void centrirajFrame() {
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    private void ucitajStanice() {
        cmbPocetnaStanica.removeAllItems();
        cmbKrajnjaStanica.removeAllItems();

        ArrayList<Stanica> listaStanica = new ArrayList<>();
        try {
            listaStanica = Kontroler.getInstance().vratiMiSveStanice();
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Stanica stanica : listaStanica) {
            cmbPocetnaStanica.addItem(stanica);
            cmbKrajnjaStanica.addItem(stanica);
        }

    }

    private void srediTabelu() {
        tablePolasci.setModel(mtp);
    }

    public void postaviVelicinuPanela(int x, int y) {
        panelKlijenta.setSize(x, y);
        panelMojeRezervacije.setSize(x, y);
        panelRezervacije.setSize(x, y);
    }

    public ArrayList<Rezervacija> getListaRezervacija() {
        return listaRezervacija;
    }

    public void setListaRezervacija(ArrayList<Rezervacija> listaRezervacija) {
        this.listaRezervacija = listaRezervacija;
    }

    private void ucitajMedjustanice() {
        listaMedjustanica = new ArrayList<>();
        try {
            listaMedjustanica = Kontroler.getInstance().vratiMiSveMedjustanica();
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String ispisiListu(ArrayList<MedjuStanica> lista) {
        String listaString = "";
        for (MedjuStanica medjuStanica : lista) {
            listaString += medjuStanica.getRedniBroj() + ". ";
            listaString += medjuStanica.getStanica().getNaziv();
            listaString += "\n";
        }
        return listaString;
    }

    public void pretraziPolaskeZaDatum() {
        DUGME = 1;
        Date date = null;
        try {
            date = panelDatum1.getUtilDate();
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        Stanica pocetna = (Stanica) cmbPocetnaStanica.getSelectedItem();
        Stanica krajnja = (Stanica) cmbKrajnjaStanica.getSelectedItem();

        Polazak p = new Polazak(-1, "", date, null, new Linija(-1, null, -1, -1, pocetna, krajnja, null), null);

        ArrayList<Polazak> listPolazaka = new ArrayList<>();
        try {
            listPolazaka = Kontroler.getInstance().vratiMiPolaskeZaDatumPocetnuIKrajnjuStanicu(p);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }

        mtp.ocistiTabelu();
        if (listPolazaka.isEmpty()) {
            new JOptionPaneExample().createAndDisplayGUI(this, new PanelAttention("Nema polazaka za datu realaciju!"));
            return;
        }
        mtp.setList(listPolazaka);
        tablePolasci.setModel(mtp);
    }

    private void pretraziZaDatumPolaske(Date date) {
        Polazak p = new Polazak(-1, "", date, null, null, null);
        ArrayList<Polazak> listPolazaka = new ArrayList<>();
        try {
            listPolazaka = Kontroler.getInstance().vratiMiPolaskeZaDatum(p);
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (listPolazaka.isEmpty()) {
            lblNazivTabele.setText("Nema polazaka za datum: " + smf.format(date));
            return;
        } else {
            lblNazivTabele.setText("Svi polasci za datum: " + smf.format(date));
        }
        mtp.ocistiTabelu();
        mtp.setList(listPolazaka);
        tablePolasci.setModel(mtp);
    }

    public void ulepsajTabelu(JTable tabela) {
        tabela.setRowHeight(25);
        tabela.setFocusable(false);
        tabela.setShowVerticalLines(false);
        tabela.setSelectionBackground(Color.LIGHT_GRAY);
        tabela.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tabela.getTableHeader().setOpaque(false);
        tabela.setRowHeight(25);
    }

    private void ucitajMojeRezervacije() {
        ArrayList<Rezervacija> listaRezervacija = new ArrayList<>();
        try {
            listaRezervacija = Kontroler.getInstance().vratiMojeRezervacije(new Rezervacija(k, null, null));
        } catch (Exception ex) {
            Logger.getLogger(FormaRezervacije.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (BROJ_PRIKAZA == 0) {
            if (listaRezervacija.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vasa lista rezervacija je prazna!");
            }
            BROJ_PRIKAZA++;
        }
        this.setListaRezervacija(listaRezervacija);
        mtr.setList(listaRezervacija);
        tabelMojeRezeravacije.setModel(mtr);
    }

    private void menuOdjavaSaDesneStrane() {
        Menu.add(Box.createHorizontalGlue());
        Menu.add(Box.createHorizontalGlue());
        Menu.add(jMenuOdjava);
    }

    private void ukljuciDarkMode() {
        lblWhiteMode.setVisible(true);
        lblDarkMode.setVisible(false);
        tema.blackTheme();
    }

    private void iskljuciDarkMode() {
        lblWhiteMode.setVisible(false);
        lblDarkMode.setVisible(true);
        tema.whiteTheme();
    }

    private void pokreniPanelRezervacija() {
        panelRezervacije.setVisible(true);
        panelKlijenta.setVisible(false);
        panelMojeRezervacije.setVisible(false);
    }

    private void pokreniPanelNalog() {
        panelRezervacije.setVisible(false);
        panelKlijenta.setVisible(true);
        panelMojeRezervacije.setVisible(false);

    }

    private void pokreniPanelMojeRezervacije() {
        panelRezervacije.setVisible(false);
        panelKlijenta.setVisible(false);
        panelMojeRezervacije.setVisible(true);
    }

    private void odjaviSe() {
        this.setVisible(false);
        FormaLoginRegistracija flr = new FormaLoginRegistracija();
        flr.setVisible(true);
    }
}
