/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.klijent.view.component;

import javax.swing.JLabel;

/**
 *
 * @author Stefan
 */
public class PanelSat extends javax.swing.JPanel {

 
    
    public PanelSat() {
        initComponents();
       
    }

    public JLabel getLblDatum() {
        return lblDatum;
    }

    public JLabel getLblVreme() {
        return lblVreme;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDatum = new javax.swing.JLabel();
        lblVreme = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDatum.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        lblDatum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatum.setToolTipText("");
        lblDatum.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));
        add(lblDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 240, 60));

        lblVreme.setFont(new java.awt.Font("Nirmala UI", 3, 24)); // NOI18N
        lblVreme.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVreme.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.lightGray, 2));
        add(lblVreme, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblVreme;
    // End of variables declaration//GEN-END:variables
}
