/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.stefanlezaic.zeleznice.srbije.klijent.view.component;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Stefan
 */
public class PanelUlogujSe extends javax.swing.JPanel {

    /**
     * Creates new form PanelUlogujSe
     */
    public PanelUlogujSe() {
        initComponents();
    
    }

    public JButton getBtnPrijaviSe() {
        return btnPrijaviSe;
    }

    public JLabel getLblEmailLogin() {
        return lblEmailLogin;
    }

    public JLabel getLblLoznikaLogin() {
        return lblLoznikaLogin;
    }

    public JTextField getTxtEmailLogin() {
        return txtEmailLogin;
    }

    public JPasswordField getTxtPasswordLogin() {
        return txtPasswordLogin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmailLogin = new javax.swing.JLabel();
        txtEmailLogin = new javax.swing.JTextField();
        lblLoznikaLogin = new javax.swing.JLabel();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnPrijaviSe = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblEmailLogin.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lblEmailLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblEmailLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblEmailLogin.setText("Email:");
        add(lblEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 60));

        txtEmailLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtEmailLogin.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txtEmailLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtEmailLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtEmailLogin.setOpaque(false);
        add(txtEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 250, 60));

        lblLoznikaLogin.setBackground(new java.awt.Color(102, 102, 102));
        lblLoznikaLogin.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        lblLoznikaLogin.setForeground(new java.awt.Color(0, 0, 0));
        lblLoznikaLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLoznikaLogin.setText("Lozinka:");
        add(lblLoznikaLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 230, 60));

        txtPasswordLogin.setBackground(new java.awt.Color(102, 102, 102));
        txtPasswordLogin.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        txtPasswordLogin.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtPasswordLogin.setOpaque(false);
        add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 250, 60));

        btnPrijaviSe.setBackground(new java.awt.Color(102, 102, 102));
        btnPrijaviSe.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPrijaviSe.setForeground(new java.awt.Color(0, 0, 0));
        btnPrijaviSe.setText("Prijavi se");
        btnPrijaviSe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnPrijaviSe.setOpaque(false);
        add(btnPrijaviSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 250, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrijaviSe;
    private javax.swing.JLabel lblEmailLogin;
    private javax.swing.JLabel lblLoznikaLogin;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables

     public void btnPrijaviSeMouseListener(MouseListener mouseListener) {
        btnPrijaviSe.addMouseListener(mouseListener);
    }
}
